package uz.dev.hmsproject.enums;



public enum Permissions {

    VIEW_USERS,
    CREATE_USERS,
    UPDATE_USERS,
    DELETE_USERS,
    VIEW_USER,
    FILTER_USERS,

    ROLES_CREATE,
    ROLES_READ,
    ROLES_UPDATE,
    ROLES_DELETE,

    SPECIALTIES_CREATE,
    SPECIALTIES_READ,
    SPECIALTIES_UPDATE,
    SPECIALTIES_DELETE,

    ROOMS_CREATE,
    ROOMS_READ,
    ROOMS_UPDATE,
    ROOMS_DELETE,

    DOCTORS_CREATE,
    DOCTORS_READ,
    DOCTORS_UPDATE,
    DOCTORS_DELETE,

    WORK_SCHEDULES_CREATE,
    WORK_SCHEDULES_READ,
    WORK_SCHEDULES_UPDATE,
    WORK_SCHEDULES_DELETE,

    PRICE_LIST_CREATE,
    PRICE_LIST_READ,
    PRICE_LIST_UPDATE,
    PRICE_LIST_DELETE,

    PATIENTS_CREATE,
    PATIENTS_READ,
    PATIENTS_UPDATE,
    PATIENTS_DELETE,

    APPOINTMENTS_CREATE,
    APPOINTMENTS_READ,
    APPOINTMENTS_UPDATE,
    APPOINTMENTS_DELETE,
    APPOINTMENTS_CHANGE_STATUS,

}
