package uz.dev.hmsproject.enums;

/**
 * Created by: asrorbek
 * DateTime: 6/16/25 11:50
 **/

public enum Permission {

    USERS_CREATE,
    USERS_READ,
            USERS_UPDATE,
    USERS_DELETE,

    ROLES_CREATE,
    ROLES_READ,
            ROLES_UPDATE,
    ROLES_DELETE,

    SPECIALTIES_CREATE,
    SPECIALTIES_READ,
            SPECIALTIES_UPDATE,
    SPECIALTIES_DELETE,

    ROOMS_CREATE,
    ROOMS_READ,
            ROOMS_UPDATE,
    ROOMS_DELETE,

    DOCTORS_CREATE,
    DOCTORS_READ,
            DOCTORS_UPDATE,
    DOCTORS_DELETE,

    WORK_SCHEDULES_CREATE,
    WORK_SCHEDULES_READ,
            WORK_SCHEDULES_UPDATE,
    WORK_SCHEDULES_DELETE,

    PRICE_LIST_CREATE,
    PRICE_LIST_READ,
            PRICE_LIST_UPDATE,
    PRICE_LIST_DELETE,

    PATIENTS_CREATE,
    PATIENTS_READ,
            PATIENTS_UPDATE,
    PATIENTS_DELETE,

    APPOINTMENTS_CREATE,
    APPOINTMENTS_READ,
            APPOINTMENTS_UPDATE,
    APPOINTMENTS_DELETE,



    ;
}
