package uz.dev.hmsproject.enums;

public enum Permissions {

    //USER MANAGEMENT
    VIEW_USERS,
    CREATE_USERS,
    UPDATE_USERS,
    DELETE_USERS,
    VIEW_USER,
    FILTER_USERS,

    // ROLES
    VIEW_ROLES,
    VIEW_ROLE,
    CREATE_ROLES,
    UPDATE_ROLES,
    DELETE_ROLES,

    // SPECIALTIES
    VIEW_SPECIALTIES,
    VIEW_SPECIALTY,
    CREATE_SPECIALTIES,
    UPDATE_SPECIALTIES,
    DELETE_SPECIALTIES,

    // ROOMS
    VIEW_ROOMS,
    VIEW_ROOM,
    CREATE_ROOMS,
    UPDATE_ROOMS,
    DELETE_ROOMS,

    // DOCTORS
    VIEW_DOCTORS,
    VIEW_DOCTOR,
    CREATE_DOCTORS,
    UPDATE_DOCTORS,
    DELETE_DOCTORS,
    FILTER_DOCTORS,

    // WORK SCHEDULES
    VIEW_WORK_SCHEDULES,
    VIEW_WORK_SCHEDULE,
    CREATE_WORK_SCHEDULES,
    UPDATE_WORK_SCHEDULES,
    DELETE_WORK_SCHEDULES,

    // PRICE LIST
    VIEW_PRICE_LIST,
    VIEW_PRICE,
    CREATE_PRICE_LIST,
    UPDATE_PRICE_LIST,
    DELETE_PRICE_LIST,
    UPDATE_PRICE_BY_SPECIALITY_ID,

    // PATIENTS
    VIEW_PATIENTS,
    VIEW_PATIENT,
    CREATE_PATIENTS,
    UPDATE_PATIENTS,
    DELETE_PATIENTS,
    PATIENTS_SEARCH,

    APPOINTMENTS_CREATE,
    APPOINTMENTS_READ,
    APPOINTMENTS_UPDATE,
    APPOINTMENTS_DELETE,
    APPOINTMENTS_CHANGE_STATUS,

    VIEW_STATISTICS,

    VIEW_LOG
}
