package uz.dev.hmsproject.enums;

import lombok.Getter;

@Getter
public enum Permissions {

    //USER MANAGEMENT
    VIEW_USERS(PageEnum.USER),
    CREATE_USER(PageEnum.USER),
    UPDATE_USER(PageEnum.USER),
    DELETE_USER(PageEnum.USER),
    VIEW_USER(PageEnum.USER),

    // ROLES
    VIEW_ROLES(PageEnum.ROLE),
    VIEW_ROLE(PageEnum.ROLE),
    CREATE_ROLE(PageEnum.ROLE),
    UPDATE_ROLE(PageEnum.ROLE),
    DELETE_ROLE(PageEnum.ROLE),

    // SPECIALTIES
    VIEW_SPECIALTIES(PageEnum.SPECIALITY),
    VIEW_SPECIALTY(PageEnum.SPECIALITY),
    CREATE_SPECIALTY(PageEnum.SPECIALITY),
    UPDATE_SPECIALTY(PageEnum.SPECIALITY),
    DELETE_SPECIALTY(PageEnum.SPECIALITY),

    // ROOMS
    VIEW_ROOMS(PageEnum.ROOM),
    VIEW_ROOM(PageEnum.ROOM),
    CREATE_ROOM(PageEnum.ROOM),
    UPDATE_ROOM(PageEnum.ROOM),
    DELETE_ROOM(PageEnum.ROOM),

    // DOCTORS
    VIEW_DOCTORS(PageEnum.DOCTOR),
    VIEW_DOCTOR(PageEnum.DOCTOR),
    CREATE_DOCTOR(PageEnum.DOCTOR),
    UPDATE_DOCTOR(PageEnum.DOCTOR),
    DELETE_DOCTOR(PageEnum.DOCTOR),

    // WORK SCHEDULES
    VIEW_WORK_SCHEDULES(PageEnum.WORK_SCHEDULER),
    VIEW_WORK_SCHEDULE(PageEnum.WORK_SCHEDULER),
    CREATE_WORK_SCHEDULE(PageEnum.WORK_SCHEDULER),
    UPDATE_WORK_SCHEDULE(PageEnum.WORK_SCHEDULER),
    DELETE_WORK_SCHEDULE(PageEnum.WORK_SCHEDULER),

    // PRICE LIST
    VIEW_PRICE_LISTS(PageEnum.PRICE_LIST),
    VIEW_PRICE_LIST(PageEnum.PRICE_LIST),
    CREATE_PRICE_LIST(PageEnum.PRICE_LIST),
    UPDATE_PRICE_LIST(PageEnum.PRICE_LIST),
    DELETE_PRICE_LIST(PageEnum.PRICE_LIST),

    // PATIENTS
    VIEW_PATIENTS(PageEnum.PATIENT),
    VIEW_PATIENT(PageEnum.PATIENT),
    CREATE_PATIENT(PageEnum.PATIENT),
    UPDATE_PATIENT(PageEnum.PATIENT),
    DELETE_PATIENT(PageEnum.PATIENT),
    PATIENTS_SEARCH(PageEnum.PATIENT),

    // APPOINTMENT
    VIEW_APPOINTMENT(PageEnum.APPOINTMENT),
    VIEW_APPOINTMENTS(PageEnum.APPOINTMENT),
    CREATE_APPOINTMENT(PageEnum.APPOINTMENT),
    UPDATE_APPOINTMENT(PageEnum.APPOINTMENT),
    DELETE_APPOINTMENT(PageEnum.APPOINTMENT),

    // STATISTICS
    VIEW_STATISTICS(PageEnum.STATISTICS),

    // LOG
    VIEW_LOG(PageEnum.LOG);

    private final PageEnum page;

    Permissions(PageEnum page) {
        this.page = page;
    }
}
