spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./db:~'
    username: sa
    password: 123 # H2 database user paroli
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    location: classpath:dev-banner.txt
myapp:
  secret-key: 'c0388696-55b0-479c-a142-a2ae7cbe269a'